 clc;close all;clear all;
 w=-pi:0.1:pi;
 z=exp(j*w); 
 z=1./z; 
 z1=0.5*exp(j*pi/4); 
 z2=0.5*exp(-j*pi/4); 
z3=conj(z1); 
z4=conj(z2); 
figure(1);
subplot(2,2,1);
zplane([z1],[1]);
title("H(z1)=+0.5exp(j*pi/4)z?1");
 subplot(2,2,2);
 zplane([z2],[1]);
 title("H(z2)=+0.5exp(-j*pi/4)z?1 "); 
 subplot(2,2,3); 
 zplane([z1],[1]); 
hold on;
zplane([z3],[1]);
title("H(z1),conj(H(z1)) ");
subplot(2,2,4); zplane([z2],[1]);
hold on;zplane([z4],[1]);
title("H(z2),conj(H(z2)) "); 
figure(2);
subplot(2,2,1);
plot(w,abs(z*z1));
title("H(z1)=+0.5exp(j*pi/4)z?1 "); 
xlabel("w");
 ylabel("|H(w)|"); 
 subplot(2,2,2);
 plot(w,abs(z*z2));
 title("H(z2)=+0.5exp(-j*pi/4)z?1 "); 
 xlabel("w");
 ylabel("|H(w)|");
 subplot(2,2,3);
 plot(w,abs(z*z3));
 title("conj(H(z1)) ");
 xlabel("w");
 ylabel("|H(w)|");
 subplot(2,2,4);
 plot(w,abs(z*z4));
 title("conj(H(z2)) ");
 xlabel("w");
 ylabel("|H(w)|"); 
