import librosa
import numpy as np
import matplotlib.pyplot as plt
import librosa.display#used to load the song
import IPython.display as ipd
w, sr = librosa.load(r'F:\book\bt18ece055_karthikeya\lab oct 55\karthik.wav')
#%loading wav file 
print(np.shape(w),sr)
print(w)
ipd.Audio(w,rate=sr)
plt.figure(1)
plt.plot(w)
w_f=np.fft.fft(w)
plt.xlabel('n')
plt.title('org/name ')
plt.ylabel('|H(n)|')
plt.figure(2)
plt.plot(w_f)
plt.xlabel('w')
plt.title('fft of org audio')
plt.ylabel('|H(w)|')
#s, sr1 = librosa.load(r'F:\book\bt18ece055_karthikeya\lab oct 55\sinew.wav')
#s=s(:,4502)
#print(np.shape(s))
#print(s)  
si=np.sin(2*np.pi*(200/sr))
w_s=w+si #% adding noise 
plt.figure(3)
plt.plot(w)
w_sf=np.fft.fft(w_s)
plt.xlabel('n')
plt.title('Noise audio')
plt.ylabel('|H(n)|')
plt.figure(4)
plt.plot(w_sf)
ipd.Audio(w_sf,rate=sr)
plt.xlabel('w')
plt.title('fft of org with noise audio')
plt.ylabel('|H(w)|')
ipd.Audio(w_sf,rate=sr)
n=np.array(range(-20000,20000))
sin_c=np.sin(2*np.pi*(1/sr)*n)/np.pi*n
plt.figure(5)
plt.plot(sin_c)
plt.xlabel('n')
plt.title('sinc')
plt.ylabel('|H(n)|')
sin_cf=np.fft.fft(sin_c)
sin_cf=(sin_cf/10000000)+10
plt.figure(6)
plt.plot(n,sin_cf)
plt.xlabel('w')
plt.title('fft of sinc')
plt.ylabel('|H(w)|')
diff=len(w_sf)-len(sin_cf)
print(diff/2)
x=np.zeros(2526)
y=np.concatenate((x,sin_cf))
z=np.concatenate((y,x))
op=w_sf*z
plt.figure(1)
plt.plot(op)
plt.xlabel('n')
plt.title('fft of filtered wave')
plt.ylabel('|H(n)|')
opf=np.fft.ifft(op)
plt.figure(2)
plt.plot(opf)
plt.xlabel('w')
plt.title('filtered wave')
plt.ylabel('|H(w)|')
ipd.Audio(opf,rate=sr)